// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyryvikogvccxxshwqja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5cnl2aWtvZ3ZjY3h4c2h3cWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4ODQzMzcsImV4cCI6MjA1NzQ2MDMzN30.Gdmor2TfQMI68P5p4vFtDmvBdpnfVxrqpPCcPSIUfx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);